
variables: variables.yml
schedules:
  - tasks: Lostfilm
    interval:
      minutes: 10
  - tasks: Baibako
    interval:
      minutes: 10
  - tasks: Tapochek
    interval:
      minutes: 10

templates:
  global:
    pathscrub: windows
    transmission:
      host: 172.17.0.2

  tvshows:
    metainfo_series: yes
    trakt_lookup: yes
    quality: 1080p
    transmission:
      path: /downloads/plex/TV Shows/{{series_name}}/Season {{series_season|pad(2)}}
    exec:
     allow_background: yes
     auto_escape: yes
     on_exit:
       for_accepted:
         - echo " `date +'%Y-%m-%d %H:%M:%S'`%{{task}}%{{series_name}} S{{series_season|pad(2)}}E{{series_episode}} {{quality}}" >> '{? path.a ?}'

  films:
    transmission:
      path: /downloads/plex/Films/{{ movie_name }} ({{ movie_year }})
    trakt_lookup:
      account: _rik_
    imdb_lookup: yes
    imdb:
      min_score: 6
      min_votes: 5000
    quality: 1080p
    upgrade:
      tracking: yes
      target: h265
    list_match:
      remove_on_match: no
      from:
        - trakt_list:
            account: _rik_
            list: watchlist
            type: movies
    exec:
     allow_background: yes
     auto_escape: yes
     on_exit:
       for_accepted:
         - echo " `date +'%Y-%m-%d %H:%M:%S'`%{{task}}%{{imdb_name}} ({{imdb_year}}) {{quality}}" >> '{? path.a ?}'
     on_exit:
       for_entries:
         - echo "{{original_title}} |   {{title}}" >> '{? path.e ?}'

  lostfilm:
    lostfilm: yes
    headers:
      cookie: '{? lostfilm.cookie ?}'
    include: lostfilm.yml
    template: tvshows

  baibako:
    rss: '{? RRSUrls.baibako ?}'
    manipulate:
      - title:
          replace:
            format: '720p'
            regexp: 'HD720p'
      - title:
          replace:
            format: '1080p'
            regexp: 'HD1080p'
      - title:
          replace:
            format: '/ '
            regexp: '/'
      - title:
          replace:
            regexp: '(.*) / (.*) / (.*) / (.*) / (.*)'
            format: '\1 - \2 \3 (\4)'
    include: baibako.yml
    template: tvshows
    accept_all: yes
    if:
      - "'Доктор Хто' in original_title": reject

  tapochek_films:
    template: films
    rss: '{? RRSUrls.tapochek ?}'
    if:
      - "'[HDrezka Studio]' in original_title": reject
      - "'[Line]' in original_title": reject
      - "'[Flarrow Films]' in original_title": reject
    manipulate:
      - title:
          replace:
            regexp: '-HEVC'
            format: ' H265'
      - title:
          replace:
            regexp: '(60 fps|iTunes|IMAX Edition|HDRezka Studio|СВ Студия|Open Matte|Лицензия|IMAX| г\.)'
            format: ''
      - title:
          replace:
            regexp: '\[\] '
            format: ''
      - title:
          replace:
            regexp: '(.*)/(.*) \((.*)\) \[(.*), (.*)\](.*)\[(.*)\]'
            format: '\2 (\3) [\4, \5] [\7]'
      - title:
          replace:
            regexp: '(.*) \((.*)\) \[(.[0-9]*)(.[А-Яа-я\,\ ]*)(.[a-zA-Z0-9\-\ ]*)\] \[(.*)\]'
            format: '\1 (\3) - \5'

tasks:
  Lostfilm:
    template: lostfilm
  Baibako:
    template: baibako
  Tapochek:
    template: tapochek_films

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes
  base_url: /
  run_v2: yes
